CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ADDRESS_LINE1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE2 VARCHAR(100),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100),
    ZIPCODE VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    PRIMARY_ADDRESS BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_ADDRESS_USER
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
                     ON DELETE CASCADE
                     ON UPDATE CASCADE
);